#!/bin/bash
export BASH_ENV='/opt/ohpc/admin/lmod/lmod/init/bash'
export CLING_STANDARD_PCH='none'
export CMAKE_PREFIX_PATH='/data6/Users/yeonjoon/miniconda3/envs/ML-torch:/data6/Users/yeonjoon/miniconda3/envs/ML-torch/x86_64-conda-linux-gnu/sysroot/usr'
export CONDA_DEFAULT_ENV='ML-torch'
export CONDA_EXE='/data6/Users/yeonjoon/miniconda3/bin/conda'
export CONDA_PREFIX='/data6/Users/yeonjoon/miniconda3/envs/ML-torch'
export CONDA_PROMPT_MODIFIER='(ML-torch) '
export CONDA_PYTHON_EXE='/data6/Users/yeonjoon/miniconda3/bin/python'
export CONDA_SHLVL='2'
export DATA6='/data6/Users/yeonjoon'
export DATA9='/data9/Users/yeonjoon'
export DISPLAY='localhost:15.0'
unset DYLD_LIBRARY_PATH
export EDITOR=''
export GV0='/gv0/Users/yeonjoon'
export HISTCONTROL='ignoredups'
export HISTSIZE='50000'
export HOME='/home/yeonjoon'
export HOSTNAME='tamsa1'
export INFOPATH='/usr/local/texlive/2021/texmf-dist/doc/info:/usr/local/texlive/2021/texmf-dist/doc/info'
unset JUPYTER_CONFIG_DIR
unset JUPYTER_PATH
export LANG='en_US.utf-8'
export LD_LIBRARY_PATH='/data6/Users/yeonjoon/software/local/lib:/data6/Users/yeonjoon/software/lib:/data6/Users/yeonjoon/software/local/lib:/data6/Users/yeonjoon/software/lib'
export LESS='-R'
export LESSOPEN='||/usr/bin/lesspipe.sh %s'
unset LIBPATH
export LMOD_CMD='/opt/ohpc/admin/lmod/lmod/libexec/lmod'
export LMOD_COLORIZE='no'
export LMOD_DIR='/opt/ohpc/admin/lmod/lmod/libexec'
export LMOD_FULL_SETTARG_SUPPORT='no'
export LMOD_PKG='/opt/ohpc/admin/lmod/lmod'
export LMOD_PREPEND_BLOCK='normal'
export LMOD_ROOT='/opt/ohpc/admin/lmod'
export LMOD_SETTARG_CMD=':'
export LMOD_SETTARG_FULL_SUPPORT='no'
export LMOD_VERSION='8.1.18'
export LOGNAME='yeonjoon'
export LSCOLORS='Gxfxcxdxbxegedabagacad'
export LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:'
export MAIL='/var/spool/mail/yeonjoon'
export MANPATH='/usr/local/texlive/2021/texmf-dist/doc/man:/usr/local/texlive/2021/texmf-dist/doc/man:/usr/local/share/man:/usr/share/man/overrides:/usr/share/man'
export MODULEPATH='/opt/ohpc/pub/modulefiles'
export MODULESHOME='/opt/ohpc/admin/lmod/lmod'
export MSM_HOME='/usr/local/MegaRAID Storage Manager'
export MSM_PRODUCT='MSM'
export OLDPWD='/data6/Users/yeonjoon'
export PAGER='less'
export PATH='/data6/Users/yeonjoon/software/node-v14.17.5-linux-x64/bin:/data6/Users/yeonjoon/software/bin:/usr/local/texlive/2021/bin/x86_64-linux:/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin:/data6/Users/yeonjoon/miniconda3/condabin:/data6/Users/yeonjoon/software/node-v14.17.5-linux-x64/bin:/data6/Users/yeonjoon/software/bin:/usr/local/bin:/usr/bin:/home/yeonjoon/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/opt/dell/srvadmin/bin:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/heroku:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/lein:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/home/yeonjoon/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/home/yeonjoon/.antigen/bundles/zsh-users/zsh-autosuggestions'
export PKG_CONFIG_PATH='/data6/Users/yeonjoon/software/lib/pkgconfig:/data6/Users/yeonjoon/software/lib/pkgconfig:'
export PWD='/data6/Users/yeonjoon/VcbMVAStudy'
unset PYTHON27PATH
unset PYTHON3PATH
export ROOTSYS='/data6/Users/yeonjoon/miniconda3/envs/ML-torch'
export SHELL='/bin/zsh'
unset SHLIB_PATH
export SHLVL='2'
export SSH_CLIENT='147.46.50.170 60132 1240'
export SSH_CONNECTION='147.46.50.170 52572 147.47.242.42 1240'
export SSH_TTY='/dev/pts/23'
export TERM='screen'
export TMUX='/tmp/tmux-5591/default,455729,0'
export TMUX_PANE='%2'
export USER='yeonjoon'
export XDG_DATA_DIRS='/home/yeonjoon/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share'
export XDG_RUNTIME_DIR='/run/user/5591'
export XDG_SESSION_ID='307'
export LC_ALL='en_US.utf-8'
export LC_CTYPE='UTF-8'
export CONDA_PREFIX_1='/data6/Users/yeonjoon/miniconda3'
export ADDR2LINE='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-addr2line'
export AR='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-ar'
export AS='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-as'
export CXXFILT='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-c++filt'
export ELFEDIT='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-elfedit'
export GPROF='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gprof'
export LD='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-ld'
export LD_GOLD='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-ld.gold'
export NM='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-nm'
export OBJCOPY='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-objcopy'
export OBJDUMP='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-objdump'
export RANLIB='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-ranlib'
export READELF='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-readelf'
export SIZE='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-size'
export STRINGS='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-strings'
export STRIP='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-strip'
export CONDA_BACKUP_HOST='tamsa1'
export HOST='x86_64-conda-linux-gnu'
export BUILD='x86_64-conda-linux-gnu'
export CONDA_TOOLCHAIN_HOST='x86_64-conda-linux-gnu'
export CONDA_TOOLCHAIN_BUILD='x86_64-conda-linux-gnu'
export CC='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-cc'
export CPP='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-cpp'
export GCC='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gcc'
export GCC_AR='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gcc-ar'
export GCC_NM='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gcc-nm'
export GCC_RANLIB='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gcc-ranlib'
export CPPFLAGS='-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-torch/include'
export CFLAGS='-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-torch/include'
export LDFLAGS='-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/data6/Users/yeonjoon/miniconda3/envs/ML-torch/lib -Wl,-rpath-link,/data6/Users/yeonjoon/miniconda3/envs/ML-torch/lib -L/data6/Users/yeonjoon/miniconda3/envs/ML-torch/lib'
export DEBUG_CPPFLAGS='-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-torch/include'
export DEBUG_CFLAGS='-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-torch/include'
unset CONDA_BACKUP_CMAKE_PREFIX_PATH
export CONDA_BUILD_SYSROOT='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/x86_64-conda-linux-gnu/sysroot'
export CC_FOR_BUILD='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-cc'
export build_alias='x86_64-conda-linux-gnu'
export host_alias='x86_64-conda-linux-gnu'
export CMAKE_ARGS='-DCMAKE_AR=/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-strip'
export GFORTRAN='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gfortran'
export F95='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-f95'
export FC_FOR_BUILD='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gfortran'
export FFLAGS='-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-torch/include'
export FORTRANFLAGS='-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-torch/include'
export DEBUG_FFLAGS='-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-torch/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe'
export DEBUG_FORTRANFLAGS='-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-torch/include -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe'
export FC='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gfortran'
export F77='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gfortran'
export F90='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-gfortran'
export CXX='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-c++'
export GXX='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-g++'
export CXXFLAGS='-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-torch/include'
export DEBUG_CXXFLAGS='-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-torch/include'
export CXX_FOR_BUILD='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/bin/x86_64-conda-linux-gnu-c++'
export PYTHIA8='/data6/Users/yeonjoon/miniconda3/envs/ML-torch'
export PYTHIA8_DIR='/data6/Users/yeonjoon/miniconda3/envs/ML-torch'
export PYTHIA8DATA='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/share/Pythia8/xmldoc'
unset CONDA_BACKUP_ROOTSYS
export CONDA_MKL_INTERFACE_LAYER_BACKUP=''
export MKL_INTERFACE_LAYER='LP64,GNU'
export GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=''
export GSETTINGS_SCHEMA_DIR='/data6/Users/yeonjoon/miniconda3/envs/ML-torch/share/glib-2.0/schemas'
