#!/bin/bash
export BASH_ENV='/opt/ohpc/admin/lmod/lmod/init/bash'
export CLING_STANDARD_PCH='none'
export CMAKE_PREFIX_PATH='/data6/Users/yeonjoon/miniconda3/envs/ML-keras:/data6/Users/yeonjoon/miniconda3/envs/ML-keras/x86_64-conda-linux-gnu/sysroot/usr'
export CONDA_DEFAULT_ENV='ML-keras'
export CONDA_EXE='/data6/Users/yeonjoon/miniconda3/bin/conda'
export CONDA_PREFIX='/data6/Users/yeonjoon/miniconda3/envs/ML-keras'
export CONDA_PROMPT_MODIFIER='(ML-keras) '
export CONDA_PYTHON_EXE='/data6/Users/yeonjoon/miniconda3/bin/python'
export CONDA_SHLVL='2'
export DATA6='/data6/Users/yeonjoon'
export DATA9='/data9/Users/yeonjoon'
export DISPLAY='localhost:15.0'
unset DYLD_LIBRARY_PATH
export EDITOR='nvim'
export GV0='/gv0/Users/yeonjoon'
export HISTCONTROL='ignoredups'
export HISTSIZE='50000'
export HOME='/home/yeonjoon'
export HOSTNAME='tamsa1'
export INFOPATH='/usr/local/texlive/2021/texmf-dist/doc/info:/usr/local/texlive/2021/texmf-dist/doc/info'
unset JUPYTER_CONFIG_DIR
unset JUPYTER_PATH
export LANG='en_US.utf-8'
export LD_LIBRARY_PATH='/data6/Users/yeonjoon/software/local/lib:/data6/Users/yeonjoon/software/lib:/data6/Users/yeonjoon/software/local/lib:/data6/Users/yeonjoon/software/lib'
export LESS='-R'
export LESSOPEN='||/usr/bin/lesspipe.sh %s'
unset LIBPATH
export LMOD_CMD='/opt/ohpc/admin/lmod/lmod/libexec/lmod'
export LMOD_COLORIZE='no'
export LMOD_DIR='/opt/ohpc/admin/lmod/lmod/libexec'
export LMOD_FULL_SETTARG_SUPPORT='no'
export LMOD_PKG='/opt/ohpc/admin/lmod/lmod'
export LMOD_PREPEND_BLOCK='normal'
export LMOD_ROOT='/opt/ohpc/admin/lmod'
export LMOD_SETTARG_CMD=':'
export LMOD_SETTARG_FULL_SUPPORT='no'
export LMOD_VERSION='8.1.18'
export LOGNAME='yeonjoon'
export LSCOLORS='Gxfxcxdxbxegedabagacad'
export LS_COLORS='rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:'
export MAIL='/var/spool/mail/yeonjoon'
export MANPATH='/usr/local/texlive/2021/texmf-dist/doc/man:/usr/local/texlive/2021/texmf-dist/doc/man:/usr/local/share/man:/usr/share/man/overrides:/usr/share/man'
export MODULEPATH='/opt/ohpc/pub/modulefiles'
export MODULESHOME='/opt/ohpc/admin/lmod/lmod'
export MSM_HOME='/usr/local/MegaRAID Storage Manager'
export MSM_PRODUCT='MSM'
export OLDPWD='/home/yeonjoon'
export PAGER='less'
export PATH='/usr/local/texlive/2021/bin/x86_64-linux:/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin:/data6/Users/yeonjoon/miniconda3/condabin:/usr/local/bin:/usr/bin:/home/yeonjoon/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/opt/dell/srvadmin/bin:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/heroku:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/lein:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/home/yeonjoon/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/home/yeonjoon/.antigen/bundles/zsh-users/zsh-autosuggestions'
export PKG_CONFIG_PATH='/data6/Users/yeonjoon/software/lib/pkgconfig:/data6/Users/yeonjoon/software/lib/pkgconfig:'
export PWD='/data6/Users/yeonjoon/VcbMVAStudy'
unset PYTHON27PATH
unset PYTHON3PATH
export ROOTSYS='/data6/Users/yeonjoon/miniconda3/envs/ML-keras'
export SHELL='/bin/zsh'
unset SHLIB_PATH
export SHLVL='2'
export SSH_CLIENT='147.46.50.170 63982 1240'
export SSH_CONNECTION='147.46.50.170 52382 147.47.242.42 1240'
export SSH_TTY='/dev/pts/4'
export TERM='xterm-256color'
export TERM_PROGRAM='tmux'
export TERM_PROGRAM_VERSION='next-3.4'
export TMUX='/tmp/tmux-5591/default,1750586,2'
export TMUX_PANE='%2'
export USER='yeonjoon'
export XDG_DATA_DIRS='/home/yeonjoon/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share'
export XDG_RUNTIME_DIR='/run/user/5591'
export XDG_SESSION_ID='28197'
export LC_ALL='en_US.utf-8'
export LC_CTYPE='UTF-8'
export CONDA_PREFIX_1='/data6/Users/yeonjoon/miniconda3'
export ADDR2LINE='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-addr2line'
export AR='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-ar'
export AS='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-as'
export CXXFILT='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-c++filt'
export ELFEDIT='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-elfedit'
export GPROF='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gprof'
export LD='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-ld'
export LD_GOLD='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-ld.gold'
export NM='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-nm'
export OBJCOPY='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-objcopy'
export OBJDUMP='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-objdump'
export RANLIB='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-ranlib'
export READELF='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-readelf'
export SIZE='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-size'
export STRINGS='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-strings'
export STRIP='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-strip'
export CONDA_BACKUP_HOST='tamsa1'
export HOST='x86_64-conda-linux-gnu'
export BUILD='x86_64-conda-linux-gnu'
export CONDA_TOOLCHAIN_HOST='x86_64-conda-linux-gnu'
export CONDA_TOOLCHAIN_BUILD='x86_64-conda-linux-gnu'
export CC='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-cc'
export CPP='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-cpp'
export GCC='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gcc'
export GCC_AR='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gcc-ar'
export GCC_NM='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gcc-nm'
export GCC_RANLIB='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gcc-ranlib'
export CPPFLAGS='-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-keras/include'
export CFLAGS='-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-keras/include'
export LDFLAGS='-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/data6/Users/yeonjoon/miniconda3/envs/ML-keras/lib -Wl,-rpath-link,/data6/Users/yeonjoon/miniconda3/envs/ML-keras/lib -L/data6/Users/yeonjoon/miniconda3/envs/ML-keras/lib'
export DEBUG_CPPFLAGS='-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-keras/include'
export DEBUG_CFLAGS='-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-keras/include'
unset CONDA_BACKUP_CMAKE_PREFIX_PATH
export CONDA_BUILD_SYSROOT='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/x86_64-conda-linux-gnu/sysroot'
export CC_FOR_BUILD='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-cc'
export build_alias='x86_64-conda-linux-gnu'
export host_alias='x86_64-conda-linux-gnu'
export CMAKE_ARGS='-DCMAKE_AR=/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-strip'
export GFORTRAN='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gfortran'
export F95='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-f95'
export FC_FOR_BUILD='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gfortran'
export FFLAGS='-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-keras/include'
export FORTRANFLAGS='-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-keras/include'
export DEBUG_FFLAGS='-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-keras/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe'
export DEBUG_FORTRANFLAGS='-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-keras/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe'
export FC='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gfortran'
export F77='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gfortran'
export F90='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-gfortran'
export CXX='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-c++'
export GXX='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-g++'
export CXXFLAGS='-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-keras/include'
export DEBUG_CXXFLAGS='-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /data6/Users/yeonjoon/miniconda3/envs/ML-keras/include'
export CXX_FOR_BUILD='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/bin/x86_64-conda-linux-gnu-c++'
export PYTHIA8='/data6/Users/yeonjoon/miniconda3/envs/ML-keras'
export PYTHIA8_DIR='/data6/Users/yeonjoon/miniconda3/envs/ML-keras'
export PYTHIA8DATA='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/share/Pythia8/xmldoc'
export GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=''
export GSETTINGS_SCHEMA_DIR='/data6/Users/yeonjoon/miniconda3/envs/ML-keras/share/glib-2.0/schemas'
