#!/bin/bash
export AS='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-as'
export CUBACORES='1'
export AR='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-ar'
export MANPATH='/usr/local/texlive/2021/texmf-dist/doc/man:/usr/local/texlive/2021/texmf-dist/doc/man:/usr/local/share/man:/usr/share/man/overrides:/usr/share/man'
export LDFLAGS='-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/data9/Users/yeonjoon/miniconda3/envs/cms-py3/lib -Wl,-rpath-link,/data9/Users/yeonjoon/miniconda3/envs/cms-py3/lib -L/data9/Users/yeonjoon/miniconda3/envs/cms-py3/lib'
export XDG_SESSION_ID='148538'
export HOSTNAME='tamsa1'
export GCC_NM='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gcc-nm'
export TERM_PROGRAM='tmux'
export TERM='xterm-256color'
export SHELL='/bin/zsh'
export HOST='x86_64-conda-linux-gnu'
export HISTSIZE='50000'
export LMOD_ROOT='/opt/ohpc/admin/lmod'
export NM='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-nm'
export CPPFLAGS='-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /data9/Users/yeonjoon/miniconda3/envs/cms-py3/include'
export SSH_CLIENT='147.46.50.170 50202 1240'
export TMPDIR='/tmp'
export CONDA_SHLVL='4'
export OPENBLAS_NUM_THREADS='1'
export CONDA_PROMPT_MODIFIER='(cms-py3) '
export TERM_PROGRAM_VERSION='next-3.4'
export SIZE='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-size'
export GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=''
export LMOD_PKG='/opt/ohpc/admin/lmod/lmod'
export OLDPWD='/var/lib/condor/execute/dir_26308'
export LMOD_VERSION='8.1.18'
export CXX_FOR_BUILD='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-c++'
export SSH_TTY='/dev/pts/0'
export LC_ALL='en_US.utf-8'
export GFORTRAN='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gfortran'
export USER='yeonjoon'
export LD_LIBRARY_PATH='/data6/Users/yeonjoon/software/local/lib:/data6/Users/yeonjoon/software/lib:/data6/Users/yeonjoon/software/local/lib:/data6/Users/yeonjoon/software/lib:/data6/Users/yeonjoon/software/local/lib:/data6/Users/yeonjoon/software/lib'
export LS_COLORS='rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:'
export TEMP='/tmp'
export CONDA_BACKUP_HOST='tamsa1'
export BATCH_SYSTEM='HTCondor'
export CONDA_TOOLCHAIN_BUILD='x86_64-conda-linux-gnu'
export CONDA_EXE='/data9/Users/yeonjoon/miniconda3/bin/conda'
export FC_FOR_BUILD='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gfortran'
export JULIA_NUM_THREADS='1'
export WtoCB_PATH='/gv0/Users/yeonjoon/'
export DEBUG_FORTRANFLAGS='-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data9/Users/yeonjoon/miniconda3/envs/cms-py3/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe'
export CXXFLAGS='-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data9/Users/yeonjoon/miniconda3/envs/cms-py3/include'
export MSM_PRODUCT='MSM'
export LD_GOLD='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-ld.gold'
export GV0='/gv0/Users/yeonjoon'
export PAGER='less'
export CONDA_TOOLCHAIN_HOST='x86_64-conda-linux-gnu'
export STRINGS='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-strings'
export CONDA_BUILD_SYSROOT='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/x86_64-conda-linux-gnu/sysroot'
export TMUX='/tmp/tmux-5591/default,2895572,0'
export CPP='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-cpp'
export LMOD_PREPEND_BLOCK='normal'
export LSCOLORS='Gxfxcxdxbxegedabagacad'
export CXXFILT='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-c++filt'
export CONDA_PREFIX_1='/home/yeonjoon/miniconda3'
export MAIL='/var/spool/mail/yeonjoon'
export PATH='/data6/Users/yeonjoon/software/node-v14.17.5-linux-x64/bin:/data6/Users/yeonjoon/software/bin:/data6/Users/yeonjoon/software/node-v14.17.5-linux-x64/bin:/data6/Users/yeonjoon/software/bin:/usr/local/texlive/2021/bin/x86_64-linux:/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin:/home/yeonjoon/miniconda3/condabin:/usr/local/bin:/usr/bin:/home/yeonjoon/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/opt/dell/srvadmin/bin:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/heroku:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/lein:/home/yeonjoon/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/home/yeonjoon/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/home/yeonjoon/.antigen/bundles/zsh-users/zsh-autosuggestions'
export TF_NUM_THREADS='1'
export GSETTINGS_SCHEMA_DIR='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/share/glib-2.0/schemas'
export CONDA_PREFIX_3='/data9/Users/yeonjoon/miniconda3'
export CONDA_PREFIX_2='/data6/Users/yeonjoon/software/miniconda3'
export MKL_NUM_THREADS='1'
export LMOD_SETTARG_CMD=':'
export CONDA_PREFIX='/data9/Users/yeonjoon/miniconda3/envs/cms-py3'
export DEBUG_CXXFLAGS='-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /data9/Users/yeonjoon/miniconda3/envs/cms-py3/include'
export BUILD='x86_64-conda-linux-gnu'
export LD='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-ld'
export PYTHIA8='/data9/Users/yeonjoon/miniconda3/envs/cms-py3'
export F90='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gfortran'
export PWD='/data6/Users/yeonjoon/VcbMVAStudy'
export CUDA_VISIBLE_DEVICES='GPU-ebb73fb1'
export NUMEXPR_NUM_THREADS='1'
export STRIP='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-strip'
export CMAKE_ARGS='-DCMAKE_AR=/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-strip'
export ELFEDIT='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-elfedit'
export EDITOR='nvim'
export LANG='en_US.utf-8'
export F95='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-f95'
export GCC_RANLIB='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gcc-ranlib'
export CLING_STANDARD_PCH='none'
export MODULEPATH='/opt/ohpc/pub/modulefiles'
export DEBUG_FFLAGS='-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data9/Users/yeonjoon/miniconda3/envs/cms-py3/include -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe'
export TMUX_PANE='%3'
export F77='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gfortran'
export LMOD_CMD='/opt/ohpc/admin/lmod/lmod/libexec/lmod'
export GOMAXPROCS='1'
export CXX='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-c++'
export ROOTSYS='/data9/Users/yeonjoon/miniconda3/envs/cms-py3'
export CC_FOR_BUILD='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-cc'
export HISTCONTROL='ignoredups'
export OBJCOPY='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-objcopy'
export SHLVL='3'
export HOME='/home/yeonjoon'
export FORTRANFLAGS='-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data9/Users/yeonjoon/miniconda3/envs/cms-py3/include'
export DEBUG_CPPFLAGS='-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /data9/Users/yeonjoon/miniconda3/envs/cms-py3/include'
export CFLAGS='-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data9/Users/yeonjoon/miniconda3/envs/cms-py3/include'
export DATA9='/data9/Users/yeonjoon'
export FC='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gfortran'
export MSM_HOME='/usr/local/MegaRAID Storage Manager'
export GCC='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gcc'
export BASH_ENV='/opt/ohpc/admin/lmod/lmod/init/bash'
export LOGNAME='yeonjoon'
export LESS='-R'
export ADDR2LINE='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-addr2line'
export CONDA_PYTHON_EXE='/data9/Users/yeonjoon/miniconda3/bin/python'
export TMP='/tmp'
export LC_CTYPE='UTF-8'
export build_alias='x86_64-conda-linux-gnu'
export SSH_CONNECTION='147.46.50.170 54681 147.47.242.42 1240'
export XDG_DATA_DIRS='/home/yeonjoon/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share'
export GPU_DEVICE_ORDINAL='GPU-ebb73fb1'
export DIR_PATH='/data6/Users/yeonjoon/VcbMVAStudy'
export TMUX_PLUGIN_MANAGER_PATH='/home/yeonjoon/.tmux/plugins/'
export MODULESHOME='/opt/ohpc/admin/lmod/lmod'
export PKG_CONFIG_PATH='/data6/Users/yeonjoon/software/lib/pkgconfig:/data6/Users/yeonjoon/software/lib/pkgconfig:/data6/Users/yeonjoon/software/lib/pkgconfig:'
export LMOD_SETTARG_FULL_SUPPORT='no'
export OMP_NUM_THREADS='1'
export CONDA_DEFAULT_ENV='cms-py3'
export LESSOPEN='||/usr/bin/lesspipe.sh %s'
export RANLIB='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-ranlib'
export DEBUG_CFLAGS='-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /data9/Users/yeonjoon/miniconda3/envs/cms-py3/include'
export LMOD_FULL_SETTARG_SUPPORT='no'
export PYTHIA8_DIR='/data9/Users/yeonjoon/miniconda3/envs/cms-py3'
export INFOPATH='/usr/local/texlive/2021/texmf-dist/doc/info:/usr/local/texlive/2021/texmf-dist/doc/info'
export PYTHIA8DATA='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/share/Pythia8/xmldoc'
export CC='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-cc'
export XDG_RUNTIME_DIR='/run/user/5591'
export CMAKE_PREFIX_PATH='/data9/Users/yeonjoon/miniconda3/envs/cms-py3:/data9/Users/yeonjoon/miniconda3/envs/cms-py3/x86_64-conda-linux-gnu/sysroot/usr'
export DISPLAY='localhost:10.0'
export OMP_THREAD_LIMIT='1'
export READELF='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-readelf'
export host_alias='x86_64-conda-linux-gnu'
export LMOD_DIR='/opt/ohpc/admin/lmod/lmod/libexec'
export GCC_AR='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gcc-ar'
export OBJDUMP='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-objdump'
export LMOD_COLORIZE='no'
export GPROF='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-gprof'
export DATA6='/data6/Users/yeonjoon'
export TF_LOOP_PARALLEL_ITERATIONS='1'
export GXX='/data9/Users/yeonjoon/miniconda3/envs/cms-py3/bin/x86_64-conda-linux-gnu-g++'
export FFLAGS='-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /data9/Users/yeonjoon/miniconda3/envs/cms-py3/include'
export BASH_FUNC_module()='() {  eval $($LMOD_CMD bash "$@") && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}'
export BASH_FUNC_ml()='() {  eval $($LMOD_DIR/ml_cmd "$@")
}'
